# Generated by Django 4.2.14 on 2024-07-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_width', models.IntegerField(default=227)),
                ('page_higth', models.IntegerField(default=1350)),
                ('padding', models.IntegerField(default=9)),
                ('font', models.FileField(blank=True, null=True, upload_to='media')),
                ('toko', models.CharField(default='Toko Kue', max_length=100)),
            ],
        ),
    ]
