# Generated by Django 4.2.14 on 2024-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='font_size',
            field=models.IntegerField(default=12),
        ),
    ]
