# Generated by Django 4.2.10 on 2024-07-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_main_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='brand',
            field=models.CharField(default='Brand Test', max_length=100),
        ),
    ]
