# Generated by Django 5.0.7 on 2024-10-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='alamat',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='password_wifi',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='telp',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='ucapan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='wifi',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
