# Generated by Django 5.0.7 on 2024-10-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_main_alamat_main_password_wifi_main_telp_main_ucapan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='utama',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FieldMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.IntegerField()),
                ('nama', models.CharField(blank=True, max_length=225, null=True)),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.main')),
            ],
        ),
    ]
